### ISSUE TITLE
Can't install wasabi2d with pip (win10/python 3.10.4 64 bits)

### ISSUE THREAD

**Issue by mentat51** [lordmauve/wasabi2d#74]
py -m pip install wasabi2d

Collecting wasabi2d
  Using cached wasabi2d-1.4.0-py3-none-any.whl (298 kB)
Collecting bresenham==0.2.*
  Using cached bresenham-0.2.1-py3-none-any.whl (3.7 kB)
Collecting wasabi2d
  Using cached wasabi2d-1.3.0-py3-none-any.whl (259 kB)
Collecting moderngl<5.6,>=5.5.4
  Using cached moderngl-5.5.4.tar.gz (115 kB)
  Preparing metadata (setup.py) ... done
Collecting pygame==2.0.0.dev6
  Using cached pygame-2.0.0.dev6.tar.gz (3.7 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]

      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\sylvain\AppData\Local\Temp\pip-install-77p0fm1v\pygame_0b7a3de3231b4b28a933f65d784bc66c\setup.py", line 258, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "C:\Users\sylvain\AppData\Local\Temp\pip-install-77p0fm1v\pygame_0b7a3de3231b4b28a933f65d784bc66c\buildconfig\config.py", line 208, in main
          deps = CFG.main(**kwds)
        File "C:\Users\sylvain\AppData\Local\Temp\pip-install-77p0fm1v\pygame_0b7a3de3231b4b28a933f65d784bc66c\buildconfig\config_win.py", line 559, in main
          and download_win_prebuilt.ask(**download_kwargs):
        File "C:\Users\sylvain\AppData\Local\Temp\pip-install-77p0fm1v\pygame_0b7a3de3231b4b28a933f65d784bc66c\buildconfig\download_win_prebuilt.py", line 269, in ask
          update(x86=x86, x64=x64, sdl2=sdl2)
        File "C:\Users\sylvain\AppData\Local\Temp\pip-install-77p0fm1v\pygame_0b7a3de3231b4b28a933f65d784bc66c\buildconfig\download_win_prebuilt.py", line 252, in update
          download_prebuilts(download_dir, x86=x86, x64=x64, sdl2=sdl2)
        File "C:\Users\sylvain\AppData\Local\Temp\pip-install-77p0fm1v\pygame_0b7a3de3231b4b28a933f65d784bc66c\buildconfig\download_win_prebuilt.py", line 101, in download_prebuilts
          download_sha1_unzip(url, checksum, temp_dir, 1)
        File "C:\Users\sylvain\AppData\Local\Temp\pip-install-77p0fm1v\pygame_0b7a3de3231b4b28a933f65d784bc66c\buildconfig\download_win_prebuilt.py", line 37, in download_sha1_unzip
          raise ValueError(
      ValueError: url:https://www.ijg.org/files/jpegsr9c.zip should have checksum:9ca086c960ffc4bff821ba194c8d0a15f69eae09: Has:1dd1a5c4e08392684b25d8f6cfd7d670b5d9db99:
      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.10-VC.zip 0bbac0106358dc99b8ba2401ae6a1c10d3927ca9
      Unzipping :prebuilt_downloads\SDL2-devel-2.0.10-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.14-VC.zip c64d90c1f7d1bb3f3dcfcc255074611f017cdcc4
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.0.14-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip 9097148f4529cf19f805ccd007618dec280f0ecc
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.0.4-VC.zip:
      Downloading... https://www.ijg.org/files/jpegsr9c.zip 9ca086c960ffc4bff821ba194c8d0a15f69eae09

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Chufretalas** [comment]
Got exactly the same problem here in **win11/python 3.11/pip 22.3**

Output of running `pip install wasabi2d` on a venv with only requests installed (I installed requests because the last error I got before that asked for it):

```
Collecting wasabi2d
  Using cached wasabi2d-1.4.0-py3-none-any.whl (298 kB)
  Using cached wasabi2d-1.3.0-py3-none-any.whl (259 kB)
Collecting pygame==2.0.0.dev6
  Using cached pygame-2.0.0.dev6.tar.gz (3.7 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]


      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\marco\AppData\Local\Temp\pip-install-5x7_hw_g\pygame_cb8891d2164f4256beb0f903bd13cc91\setup.py", line 258, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "C:\Users\marco\AppData\Local\Temp\pip-install-5x7_hw_g\pygame_cb8891d2164f4256beb0f903bd13cc91\buildconfig\config.py", line 208, in main
          deps = CFG.main(**kwds)
                 ^^^^^^^^^^^^^^^^
        File "C:\Users\marco\AppData\Local\Temp\pip-install-5x7_hw_g\pygame_cb8891d2164f4256beb0f903bd13cc91\buildconfig\config_win.py", line 559, in main
          and download_win_prebuilt.ask(**download_kwargs):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\marco\AppData\Local\Temp\pip-install-5x7_hw_g\pygame_cb8891d2164f4256beb0f903bd13cc91\buildconfig\download_win_prebuilt.py", line 269, in ask
          update(x86=x86, x64=x64, sdl2=sdl2)
        File "C:\Users\marco\AppData\Local\Temp\pip-install-5x7_hw_g\pygame_cb8891d2164f4256beb0f903bd13cc91\buildconfig\download_win_prebuilt.py", line 252, in update
          download_prebuilts(download_dir, x86=x86, x64=x64, sdl2=sdl2)
        File "C:\Users\marco\AppData\Local\Temp\pip-install-5x7_hw_g\pygame_cb8891d2164f4256beb0f903bd13cc91\buildconfig\download_win_prebuilt.py", line 101, in download_prebuilts
          download_sha1_unzip(url, checksum, temp_dir, 1)
        File "C:\Users\marco\AppData\Local\Temp\pip-install-5x7_hw_g\pygame_cb8891d2164f4256beb0f903bd13cc91\buildconfig\download_win_prebuilt.py", line 37, in download_sha1_unzip
          raise ValueError(
      ValueError: url:https://www.ijg.org/files/jpegsr9c.zip should have checksum:9ca086c960ffc4bff821ba194c8d0a15f69eae09: Has:1dd1a5c4e08392684b25d8f6cfd7d670b5d9db99:
      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.10-VC.zip 0bbac0106358dc99b8ba2401ae6a1c10d3927ca9
      Unzipping :prebuilt_downloads\SDL2-devel-2.0.10-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.14-VC.zip c64d90c1f7d1bb3f3dcfcc255074611f017cdcc4
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.0.14-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip 9097148f4529cf19f805ccd007618dec280f0ecc
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.0.4-VC.zip:
      Downloading... https://www.ijg.org/files/jpegsr9c.zip 9ca086c960ffc4bff821ba194c8d0a15f69eae09

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Chufretalas** [comment]
I tried using python 3.8.10 and it worked fine. Seens to be a problem with the pygame version wasabi2d uses not supporting newer versions of python.  
You can actually install pygame in python 3.11 with `pip install pygame --pre`, but this downloads version **pygame-2.1.3.dev8** and the version that `pip install wasabi2d` tries to install is **pygame-2.0.0.dev6**. So I think it won't be long until we can use python 3.10 or 3.11.
